FROM ubuntu:20.04

# update、vim、日本語化対応
RUN apt-get update && \
    apt-get install -y vim && \
    apt-get install -y language-pack-ja-base language-pack-ja locales && \
    locale-gen ja_JP.UTF-8 && \
    echo "export LANG='ja_JP.UTF-8'" >> "${HOME}/.profile" && \
    echo "export LANG='ja_JP.UTF-8'" >> "${HOME}/.bashrc"

ENV LANG "ja_JP.UTF-8"
ENV LC_CTYPE "ja_JP.UTF-8"

# postfix、SASL2、mailutils、nkfをインストール
RUN apt install postfix sasl2-bin mailutils nkf  -y

# 掃除
RUN apt-get clean

# コンテナ起動時のスクリプト
COPY ./entrypoint.sh  /
RUN chmod 700 /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
